package utils

var gruntDict = map[string]string{
    "4":  "grunt",
    "5":  "grunt",
    "6":  "bug",
    "7":  "bug",
    "48": "ghost",
    "47": "ghost",
    "10": "dark",
    "11": "dark",
    "12": "dragon",
    "13": "dragon",
    "14": "fairy",
    "15": "fairy",
    "16": "fighting",
    "17": "fighting",
    "18": "fire",
    "19": "fire",
    "20": "flying",
    "21": "flying",
    "22": "grass",
    "23": "grass",
    "24": "ground",
    "25": "ground",
    "26": "ice",
    "27": "ice",
    "28": "metal",
    "29": "metal",
    "30": "normal",
    "31": "normal",
    "32": "poison",
    "33": "poison",
    "34": "psychic",
    "35": "psychic",
    "36": "rock",
    "37": "rock",
    "38": "water",
    "39": "water",
    "49": "electric",
    "50": "electric",
    "41": "cliff",
    "42": "arlo",
    "43": "sierra",
    "44": "giovanni",
}

func GetGruntFromID(id string) string {
    return gruntDict[id]
}
